---
{% include 'roles/ansible-role/templates/header.j2' %}
#
# Defaults for role registrar
#
REGISTRAR_GIT_IDENTITY: !!null

# depends upon Newrelic being enabled via COMMON_ENABLE_NEWRELIC
# and a key being provided via NEWRELIC_LICENSE_KEY
REGISTRAR_NEWRELIC_APPNAME: "{{ '{{ COMMON_ENVIRONMENT }}' }}-{{ '{{ COMMON_DEPLOYMENT }}' }}-{{ '{{' }} registrar_service_name }}"
REGISTRAR_PIP_EXTRA_ARGS: "-i {{ '{{ COMMON_PYPI_MIRROR_URL }}' }}"
REGISTRAR_NGINX_PORT: 18734
REGISTRAR_SSL_NGINX_PORT: 48734

REGISTRAR_DEFAULT_DB_NAME: 'registrar'
REGISTRAR_MYSQL: 'localhost'
# MySQL usernames are limited to 16 characters
REGISTRAR_MYSQL_USER: 'registrar001'
REGISTRAR_MYSQL_PASSWORD: 'password'
REGISTRAR_MYSQL_OPTIONS:
  connect_timeout: 10

REGISTRAR_DATABASES:
  # rw user
  default:
    ENGINE: 'django.db.backends.mysql'
    NAME: '{{ '{{' }} REGISTRAR_DEFAULT_DB_NAME }}'
    USER: '{{ '{{' }} REGISTRAR_MYSQL_USER }}'
    PASSWORD: '{{ '{{' }} REGISTRAR_MYSQL_PASSWORD }}'
    HOST: '{{ '{{' }} REGISTRAR_MYSQL }}'
    PORT: '3306'
    ATOMIC_REQUESTS: true
    CONN_MAX_AGE: 60
    OPTIONS: '{{ '{{' }} REGISTRAR_MYSQL_OPTIONS }}'


REGISTRAR_MEMCACHE: [ 'memcache' ]

REGISTRAR_CACHES:
  default:
    BACKEND:  'django.core.cache.backends.memcached.MemcachedCache'
    KEY_PREFIX: '{{ '{{' }} registrar_service_name }}'
    LOCATION: '{{ '{{' }} REGISTRAR_MEMCACHE }}'

REGISTRAR_VERSION: "master"
REGISTRAR_DJANGO_SETTINGS_MODULE: "registrar.settings.production"
REGISTRAR_URL_ROOT: 'http://registrar:18734'
REGISTRAR_LOGOUT_URL: '{{ '{{' }} REGISTRAR_URL_ROOT }}/logout/'
REGISTRAR_OAUTH_URL_ROOT: '{{ EDXAPP_LMS_ISSUER | default("http://127.0.0.1:8000/oauth2") }}'
REGISTRAR_OAUTH2_LOGOUT_URL: '{{ EDXAPP_LMS_ROOT_URL | default("http://127.0.0.1:8000") }}/logout'

REGISTRAR_SECRET_KEY: 'Your secret key here'
REGISTRAR_TIME_ZONE: 'UTC'
REGISTRAR_LANGUAGE_CODE: 'en-us'

# Used to automatically configure OAuth2 Client
REGISTRAR_SOCIAL_AUTH_EDX_OAUTH2_KEY : 'registrar-sso-key'
REGISTRAR_SOCIAL_AUTH_EDX_OAUTH2_SECRET : 'registrar-sso-secret'
REGISTRAR_BACKEND_SERVICE_EDX_OAUTH2_KEY : 'registrar-backend-service-key'
REGISTRAR_BACKEND_SERVICE_EDX_OAUTH2_SECRET : 'registrar-backend-service-secret'
REGISTRAR_SOCIAL_AUTH_REDIRECT_IS_HTTPS: false
# Remove these OIDC settings post-DOP-removal from credentials.
REGISTRAR_SOCIAL_AUTH_EDX_OIDC_KEY : 'registrar-key'
REGISTRAR_SOCIAL_AUTH_EDX_OIDC_SECRET : 'registrar-secret'

REGISTRAR_PLATFORM_NAME: 'Your Platform Name Here'

REGISTRAR_SERVICE_CONFIG:
  SECRET_KEY: '{{ '{{' }} REGISTRAR_SECRET_KEY }}'
  TIME_ZONE: '{{ '{{' }} REGISTRAR_TIME_ZONE }}'
  LANGUAGE_CODE: '{{ '{{' }} REGISTRAR_LANGUAGE_CODE }}'

  SOCIAL_AUTH_EDX_OAUTH2_KEY: '{{ '{{' }} REGISTRAR_SOCIAL_AUTH_EDX_OAUTH2_KEY }}'
  SOCIAL_AUTH_EDX_OAUTH2_SECRET: '{{ '{{' }} REGISTRAR_SOCIAL_AUTH_EDX_OAUTH2_SECRET }}'
  BACKEND_SERVICE_EDX_OAUTH2_KEY: '{{ '{{' }} REGISTRAR_BACKEND_SERVICE_EDX_OAUTH2_KEY }}'
  BACKEND_SERVICE_EDX_OAUTH2_SECRET: '{{ '{{' }} REGISTRAR_BACKEND_SERVICE_EDX_OAUTH2_SECRET }}'
  SOCIAL_AUTH_EDX_OAUTH2_URL_ROOT: '{{ '{{' }} REGISTRAR_OAUTH_URL_ROOT }}'
  SOCIAL_AUTH_EDX_OAUTH2_LOGOUT_URL: '{{ '{{' }} REGISTRAR_OAUTH2_LOGOUT_URL }}'
  SOCIAL_AUTH_REDIRECT_IS_HTTPS: '{{ '{{' }} REGISTRAR_SOCIAL_AUTH_REDIRECT_IS_HTTPS }}'
# Remove these OIDC settings post-DOP-removal from credentials.
  SOCIAL_AUTH_EDX_OIDC_KEY: '{{ '{{' }} REGISTRAR_SOCIAL_AUTH_EDX_OIDC_KEY }}'
  SOCIAL_AUTH_EDX_OIDC_SECRET: '{{ '{{' }} REGISTRAR_SOCIAL_AUTH_EDX_OIDC_SECRET }}'
  SOCIAL_AUTH_EDX_OIDC_ID_TOKEN_DECRYPTION_KEY: '{{ '{{' }} REGISTRAR_SOCIAL_AUTH_EDX_OIDC_SECRET }}'
  SOCIAL_AUTH_EDX_OIDC_URL_ROOT: '{{ '{{' }} REGISTRAR_OAUTH_URL_ROOT }}'
  SOCIAL_AUTH_EDX_OIDC_LOGOUT_URL: '{{ '{{' }} REGISTRAR_OAUTH2_LOGOUT_URL }}'

  STATIC_ROOT: "{{ '{{' }} COMMON_DATA_DIR }}/{{ '{{' }} registrar_service_name }}/staticfiles"
  # db config
  DATABASES: '{{ '{{' }} REGISTRAR_DATABASES }}'
  CACHES: '{{ '{{' }} REGISTRAR_CACHES }}'

  PLATFORM_NAME: '{{ '{{' }} REGISTRAR_PLATFORM_NAME }}'


REGISTRAR_REPOS:
  - PROTOCOL: "{{ '{{' }} COMMON_GIT_PROTOCOL }}"
    DOMAIN: "{{ '{{' }} COMMON_GIT_MIRROR }}"
    PATH: "{{ '{{' }} COMMON_GIT_PATH }}"
    REPO: registrar.git
    VERSION: "{{ '{{' }} REGISTRAR_VERSION }}"
    DESTINATION: "{{ '{{' }} registrar_code_dir }}"
    SSH_KEY: "{{ '{{' }} REGISTRAR_GIT_IDENTITY }}"


REGISTRAR_GUNICORN_WORKERS: "2"
REGISTRAR_GUNICORN_EXTRA: ""
REGISTRAR_GUNICORN_EXTRA_CONF: ""
REGISTRAR_GUNICORN_WORKER_CLASS: "gevent"
REGISTRAR_GUNICORN_MAX_REQUESTS: !!null

REGISTRAR_HOSTNAME: '~^((stage|prod)-)?registrar.*'

REGISTRAR_DEBIAN_EXTRA_PKGS: []

nginx_registrar_gunicorn_hosts:
  - 127.0.0.1

#
# vars are namespace with the module name.
#
registrar_role_name: registrar
registrar_venv_dir: "{{ '{{' }} registrar_home }}/venvs/{{ '{{' }} registrar_service_name }}"

registrar_environment:
  DJANGO_SETTINGS_MODULE: "{{ '{{' }} REGISTRAR_DJANGO_SETTINGS_MODULE }}"
  REGISTRAR_CFG: "{{ '{{' }} COMMON_CFG_DIR }}/{{ '{{' }} registrar_service_name }}.yml"
  PATH: "{{ '{{' }} registrar_venv_dir }}/bin:{{ '{{' }} ansible_env.PATH }}"

registrar_migration_environment:
  DJANGO_SETTINGS_MODULE: "{{ '{{' }} REGISTRAR_DJANGO_SETTINGS_MODULE }}"
  REGISTRAR_CFG: "{{ '{{' }} COMMON_CFG_DIR }}/{{ '{{' }} registrar_service_name }}.yml"
  PATH: "{{ '{{' }} registrar_venv_dir }}/bin:{{ '{{' }} ansible_env.PATH }}"
  DB_MIGRATION_USER: "{{ '{{' }} COMMON_MYSQL_MIGRATE_USER }}"
  DB_MIGRATION_PASS: "{{ '{{' }} COMMON_MYSQL_MIGRATE_PASS }}"

registrar_service_name: "registrar"
registrar_user: "{{ '{{' }} registrar_service_name }}"
registrar_home: "{{ '{{' }} COMMON_APP_DIR }}/{{ '{{' }} registrar_service_name }}"
registrar_code_dir: "{{ '{{' }} registrar_home }}/{{ '{{' }} registrar_service_name }}"

registrar_gunicorn_host: "127.0.0.1"
registrar_gunicorn_port: 8734
registrar_gunicorn_timeout: 300

registrar_log_dir: "{{ '{{' }} COMMON_LOG_DIR }}/{{ '{{' }} registrar_service_name }}"

#
# OS packages
#

registrar_debian_pkgs:
  - libmysqlclient-dev
  - libssl-dev

registrar_redhat_pkgs: []
